version: '3.8'

services:

  user:
    build: ./user/
    image: user
    entrypoint: 
      - venv/bin/python
      - start.py
    container_name: user
    environment:
      - MODULE_NAME=user
    ports:
      - 8000:8000
    networks:
      - my_network

  smart_home:
    build: ./smart_home/
    image: smart_home
    entrypoint: 
      - venv/bin/python
      - start.py
    container_name: smart_home
    environment:
      - MODULE_NAME=smart_home
    ports:
      - 8001:8001
    networks:
      - my_network

  server:
    build: ./server/
    image: server
    entrypoint:
      - venv/bin/python
      - start.py
    container_name: server
    environment:
      - MODULE_NAME=customer
    ports:
      - 8002:8002
    networks:
      - my_network

networks:
  my_network:
    driver: bridge